name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      majorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }} # To use an output in another job, you have to map it to a job output.
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # gitversion/execute step omitted for brevity
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
            versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set Connection String
      env:
        CONNECTION_STRING: ${{ secrets.ConnectionString }}
      run: echo "ConnectionStrings__ConnectionString=${{ env.CONNECTION_STRING }}" >> $GITHUB_ENV

    - name: tests
      run: dotnet test src/Tests/Nop.Tests --verbosity normal

  deploy:
    needs: [calculate-version, test]
    runs-on: ubuntu-latest
    steps:
    -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tengermese:${{ needs.calculate-version.outputs.majorMinorPatch }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az webapp config container set --name tengermese --resource-group Meseterapeuta-honlap --docker-custom-image-name vandreas73/tengermese:${{ needs.calculate-version.outputs.majorMinorPatch }}
