name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: tests
      run: dotnet test src/Tests/Nop.Tests --verbosity normal
    
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    #- name: Increment version
    #  run: |
    #    # Read the version from the file
    #    VERSION=$(cat version_number.txt)
    #    # Increment the version
    #    NEW_VERSION=$(($VERSION + 1))
    #    # Save the incremented version back to the file
    #    echo $NEW_VERSION > version_number.txt
    #    echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tengermese:${{ github.sha }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az webapp config container set --name tengermese-web-app --resource-group Meseterapeuta-honlap --docker-custom-image-name vandreas73/tengermese:${{ github.sha }}
